name: Generate Cred Instance
on:
  # Trigger on merging to main.
  push:
    branches:
      - main

jobs:
  GenerateCredInstance:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=8192
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false # Required to make github pages deployment work correctly

      - name: Install Packages ğŸ”§
        run: yarn --frozen-lockfile

      - name: Generate Frontend ğŸ—
        run: |
          yarn sourcecred site
          rm -rf ./site/{output,data,config,sourcecred.json}
          cp -r ./{output,data,config,sourcecred.json,package.json,yarn.lock} ./site/

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
